### Site Settings ###
title: Marc Vila
description: >
baseurl: ""
repository: LaQuay/marcvila.me
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Marc Vila GÃ³mez
  image: /assets/img/profile.png
  linkedin: marcvilagomez
  github: LaQuay
  scholar: dJvoBz8AAAAJ
  medium: laquay
  stackoverflow: 4314686
  # twitter: GrimmSour
  # behance           : your_username
  # dribbble          : your_username
  # email: hola@marcvila.me EDITED IN social.html
  # facebook          : your_username
  # gitlab            : your_username
  # instagram         : your_username
  # kaggle            : your_username
  # soundcloud        : your_username
  # spotify           : your_username
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  # vimeo             : your_username
  # youtube           : your_channel_name

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  hackathons:
    output: true
    permalink: /hackathons/:name

### Disqus ###
#disqus: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "hackathons"
    values:
      layout: "hackathon"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
