### Site Settings ###
title: Marc Vila
description: >-
  Hi there! I am <b>Marc Vila G贸mez</b>!
  <br>
  Software engineer. Based in Barcelona.
  <br>
  Industrial PhD student in Computer Science at <a href='https://www.upc.edu' target='_blank'>Universitat Polit猫cnica de Catalunya</a> 
  and <a href='https://www.worldsensing.com/' target='_blank'>Worldsensing</a>. 
  <br>
  If you are interested in working with me or anything similar, 
  feel free to get in touch.
  <br>锔锔锔锔<br>
  Hola! Soy <b>Marc Vila G贸mez</b>!
  <br>
  Ingeniero Software. Resido en Barcelona.
  <br>
  Estudiante de Doctorado Industrial en Ciencias de la Computaci贸n en la <a href='https://www.upc.edu' target='_blank'>Universitat Polit猫cnica de Catalunya</a> 
  y <a href='https://www.worldsensing.com/' target='_blank'>Worldsensing</a>. 
  <br>
  Si est谩s interesado/a en trabajar conmigo, o algo similar, 
  si茅ntete libre de contactarme.
  <br>锔锔锔锔<br>
  Hola! Soc <b>Marc Vila G贸mez</b>!
  <br>
  Enginyer Software. Resideixo a Barcelona.
  <br>
  Estudiant de Doctorat Industrial en Ci猫ncies de la Computaci贸 a la <a href='https://www.upc.edu' target='_blank'>Universitat Polit猫cnica de Catalunya</a> 
  i <a href='https://www.worldsensing.com/' target='_blank'>Worldsensing</a>. 
  <br>
  Si ests interessat/da en treballar amb mi, o quelcom similar,
  sentiu-vos lliure de contactar amb mi.
baseurl: ""
repository: LaQuay/marcvila.me
remote_theme: YoussefRaafatNasry/portfolYOU
open_new_tab: true # Opens external URLs in new tab (works for posts, projects and navbar only)

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

### Author Info ###
author:
  name: Marc Vila G贸mez
  image: /assets/img/profile.png
  # behance           : your_username
  # dribbble          : your_username
  # email: hola@marcvila.me EDITED IN social.html
  # facebook          : your_username
  github: LaQuay
  # gitlab            : your_username
  # instagram         : your_username
  # kaggle            : your_username
  linkedin: marcvilagomez
  medium: laquay
  # soundcloud        : your_username
  # spotify           : your_username
  stackoverflow: 4314686
  # tumblr            : your_username.tumblr.com
  # twitch            : your_username
  twitter: GrimmSour
  # vimeo             : your_username
  # youtube           : your_channel_name

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  hackathons:
    output: true
    permalink: /hackathons/:name

### Disqus ###
#disqus: your-short-name-disqus # Your website Shortname on disqus

### Analytics ###
analytics:
  enabled: false # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "hackathons"
    values:
      layout: "hackathon"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
